@startuml

class Paciente {
- numeroDeDocumento: String
- nombre: String
- edad: int
- nombreDeObraSocial: String
- particular: boolean
- medicoEspecialista: Medico
- cantidadDeEstudios: int
- cirugia: boolean
- alta: boolean
}

class Medico {
- numeroDeMatricula: String
- nombre: String
- importeBasico:  double
+ cobrar(): double
}

class Cardiologo {

+cobrar(): double
}
class Cirujano {
+cobrar(): double
}

class Dermatologo {
+cobrar(): double
}
class Generalista {
+cobrar(): double
}


Paciente *-right- Medico : -especialista
Cardiologo  --|> Medico
Cirujano  --|> Medico
Dermatologo --|> Medico
Generalista --|> Medico


@enduml